// import './01.hello';
// import './02.base_type';
// import './03.complex_type';
// import './04.ilteral';
// import './05.function_type';
// import './06.class_type';
// import './07.interface';
// import './08.unions_intersection_types';
// import './09.enum_type';
import './10.generic_type';
